# Generated by Django 4.2.4 on 2023-11-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_order_produsts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weaponts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('rerity', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
