# Generated by Django 3.2.13 on 2023-11-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_remove_worldborder_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='area',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
