# Generated by Django 3.2.13 on 2023-12-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0011_auto_20231214_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpoint',
            name='x',
            field=models.CharField(help_text='Значение азимута магнитного', max_length=250, verbose_name='Значение азимута магнитного'),
        ),
        migrations.AlterField(
            model_name='worldpoint',
            name='y',
            field=models.CharField(help_text='Значение расстояния в пар-шагах', max_length=250, verbose_name='Значение расстояния в пар-шагах'),
        ),
    ]
