# Generated by Django 3.2.13 on 2023-12-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0013_auto_20231219_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldpoint',
            name='pn',
            field=models.FloatField(default=1, help_text='Поправка направления', verbose_name='Поправка направления'),
            preserve_default=False,
        ),
    ]
