# Generated by Django 5.0 on 2023-12-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0020_worldpoint_myline_delete_pointinline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldpoint',
            name='myline',
        ),
        migrations.AddField(
            model_name='worldpoint',
            name='myline',
            field=models.ManyToManyField(blank=True, null=True, related_name='mypoints', to='geoapp.worldline'),
        ),
    ]
