# Generated by Django 5.0 on 2023-12-24 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0021_remove_worldpoint_myline_worldpoint_myline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldpoint',
            name='myline',
        ),
        migrations.CreateModel(
            name='PointInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mylines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mypoints', to='geoapp.worldline')),
                ('mypoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylines', to='geoapp.worldpoint')),
            ],
        ),
    ]
