# Generated by Django 5.0 on 2023-12-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0023_alter_worldline_location_alter_worldpoint_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldline',
            name='azimuth',
            field=models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Значение азимута магнитного'),
        ),
        migrations.AlterField(
            model_name='worldline',
            name='distance',
            field=models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Значение расстояния в пар-шагах'),
        ),
        migrations.AlterField(
            model_name='worldline',
            name='pn',
            field=models.FloatField(blank=True, default=0, verbose_name='Поправка направления'),
        ),
        migrations.AlterField(
            model_name='worldpoint',
            name='name',
            field=models.CharField(help_text='Введите название ориентира', max_length=250, verbose_name='Название ориентира'),
        ),
    ]
