# Generated by Django 5.0 on 2023-12-29 09:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0024_alter_worldline_azimuth_alter_worldline_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=28404, verbose_name='Схема движения'),
        ),
    ]
