# Generated by Django 5.0 on 2023-12-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0025_alter_worldpoint_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldline',
            options={'verbose_name_plural': 'Схема движеия по азимутам'},
        ),
        migrations.AlterModelOptions(
            name='worldpoint',
            options={'verbose_name_plural': 'Схема расположения ориентиров'},
        ),
    ]
