# Generated by Django 5.0 on 2023-12-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0029_worldline_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldline',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Shema'),
        ),
    ]
