# Generated by Django 5.0 on 2023-12-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0030_alter_worldline_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldline',
            name='name',
            field=models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Название схемы'),
        ),
        migrations.AlterField(
            model_name='worldline',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Shema'),
        ),
    ]
