# Generated by Django 5.0 on 2023-12-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0031_worldline_name_alter_worldline_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldline',
            name='name',
        ),
        migrations.RemoveField(
            model_name='worldline',
            name='slug',
        ),
    ]
