# Generated by Django 5.0 on 2024-01-03 21:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0034_tile_alter_worldline_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=28404, verbose_name='Тайловая модель'),
        ),
    ]
