# Generated by Django 5.0 on 2024-01-04 00:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0035_alter_tile_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField()),
                ('osm_id', models.IntegerField()),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(srid=28404)),
            ],
            options={
                'db_table': 'building_polygon',
            },
        ),
        migrations.CreateModel(
            name='OsmLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_id', models.IntegerField()),
                ('osm_id', models.IntegerField()),
                ('line_ref', models.IntegerField()),
                ('way_tag', models.TextField()),
                ('line_tag', models.TextField()),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=28404)),
            ],
            options={
                'db_table': 'planet_osm_line',
            },
        ),
        migrations.CreateModel(
            name='OsmNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_id', models.IntegerField()),
                ('osm_id', models.IntegerField()),
                ('node_id', models.IntegerField()),
                ('way_tag', models.TextField()),
                ('node_tag', models.TextField()),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=28404)),
            ],
            options={
                'db_table': 'planet_osm_node',
            },
        ),
        migrations.CreateModel(
            name='OsmRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.IntegerField()),
                ('osm_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('member_type', models.TextField()),
                ('role', models.TextField()),
                ('relation_tag', models.TextField()),
            ],
            options={
                'db_table': 'planet_osm_relation',
            },
        ),
        migrations.CreateModel(
            name='PlantPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.IntegerField()),
                ('osm_id', models.IntegerField()),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(srid=28404)),
            ],
            options={
                'db_table': 'plant_polygon',
            },
        ),
        migrations.DeleteModel(
            name='Tile',
        ),
    ]
