# Generated by Django 5.0 on 2024-03-04 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0037_tile_delete_buildingpolygon_delete_osmline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldline',
            name='location',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=28404, unique=True, verbose_name='Схема'),
        ),
    ]
