# Generated by Django 5.0 on 2024-03-04 19:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0038_alter_worldline_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldline',
            name='location',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=28404, verbose_name='Схема'),
        ),
    ]
