# Generated by Django 4.0.3 on 2023-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0007_worldpoint_delete_worldline'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldpoint',
            name='x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldpoint',
            name='y',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
