# Generated by Django 4.0.3 on 2023-12-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0008_worldpoint_x_worldpoint_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpoint',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldpoint',
            name='y',
            field=models.FloatField(),
        ),
    ]
