# Generated by Django 3.2.13 on 2023-12-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0009_alter_worldpoint_x_alter_worldpoint_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldpoint',
            name='x',
        ),
        migrations.RemoveField(
            model_name='worldpoint',
            name='y',
        ),
        migrations.AlterField(
            model_name='worldpoint',
            name='name',
            field=models.CharField(help_text='Название ориентира', max_length=250, verbose_name='Название ориентира'),
        ),
    ]
