# Generated by Django 3.2.13 on 2023-12-19 08:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0012_auto_20231214_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimuth', models.CharField(blank=True, default=' - ', help_text='Значение азимута магнитного', max_length=250, verbose_name='Значение азимута магнитного')),
                ('distance', models.CharField(blank=True, default=' - ', help_text='Значение расстояния в пар-шагах', max_length=250, verbose_name='Значение расстояния в пар-шагах')),
                ('location', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
        migrations.RemoveField(
            model_name='worldpoint',
            name='x',
        ),
        migrations.RemoveField(
            model_name='worldpoint',
            name='y',
        ),
    ]
