# Generated by Django 5.0 on 2023-12-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0015_auto_20231219_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mylines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mypoints', to='geoapp.worldline')),
                ('mypoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylines', to='geoapp.worldpoint')),
            ],
        ),
    ]
