# Generated by Django 5.0 on 2023-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0028_alter_worldline_options_alter_worldpoint_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldline',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Shema'),
            preserve_default=False,
        ),
    ]
