# Generated by Django 5.0 on 2023-12-30 20:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0033_worldline_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_level', models.IntegerField()),
                ('tile_column', models.IntegerField()),
                ('tile_row', models.IntegerField()),
                ('tile_data', models.BinaryField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='worldline',
            name='location',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=28404, verbose_name='Схема'),
        ),
    ]
