# Generated by Django 5.0 on 2024-01-05 16:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0036_buildingpolygon_osmline_osmnode_osmrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_level', models.IntegerField()),
                ('tile_column', models.IntegerField()),
                ('tile_row', models.IntegerField()),
                ('tile_data', models.BinaryField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=28404, verbose_name='Тайловая модель')),
            ],
            options={
                'db_table': 'tile_model',
            },
        ),
        migrations.DeleteModel(
            name='BuildingPolygon',
        ),
        migrations.DeleteModel(
            name='OsmLine',
        ),
        migrations.DeleteModel(
            name='OsmNode',
        ),
        migrations.DeleteModel(
            name='OsmRelation',
        ),
        migrations.DeleteModel(
            name='PlantPolygon',
        ),
        migrations.AlterModelOptions(
            name='pointinline',
            options={'verbose_name_plural': 'Таблица M:N'},
        ),
        migrations.AlterModelTable(
            name='pointinline',
            table='relations_model',
        ),
        migrations.AlterModelTable(
            name='worldline',
            table='lines_model',
        ),
        migrations.AlterModelTable(
            name='worldpoint',
            table='points_model',
        ),
    ]
