# Generated by Django 4.0.3 on 2024-06-06 15:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0037_tile_delete_buildingpolygon_delete_osmline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Название точек')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Импорт точек маршрута',
                'db_table': 'trek_model',
            },
        ),
    ]
