# Generated by Django 5.0 on 2024-06-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0039_importinc_importtrekline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtrekline',
            name='azimuth',
            field=models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Значение азимута магнитного'),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='distance',
            field=models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Значение расстояния в пар-шагах'),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='name',
            field=models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='pn',
            field=models.FloatField(blank=True, default=0, verbose_name='Поправка направления'),
        ),
    ]
