# Generated by Django 5.0 on 2024-06-07 02:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0044_alter_importtrek_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importinc',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='location',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Местонахождение маршрута'),
        ),
    ]
