# Generated by Django 5.0 on 2024-06-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0045_alter_importinc_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtrekline',
            name='azimuth',
            field=models.FloatField(blank=True, default=0, verbose_name='Значение азимута магнитного'),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='distance',
            field=models.FloatField(blank=True, default=0, verbose_name='Значение расстояния в пар-шагах'),
        ),
    ]
