# Generated by Django 4.0.3 on 2024-06-07 13:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0047_alter_importtrekline_azimuth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtrek',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местонахождение точки'),
        ),
        migrations.AlterField(
            model_name='importtrek',
            name='name',
            field=models.CharField(default=' - ', max_length=250, verbose_name='Название точек'),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='azimuth',
            field=models.CharField(default=' - ', max_length=250, verbose_name='Значение азимута магнитного'),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='distance',
            field=models.CharField(default=' - ', max_length=250, verbose_name='Значение расстояния в пар-шагах'),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='name',
            field=models.CharField(default=' - ', max_length=250, verbose_name='Название участка маршрута'),
        ),
        migrations.AlterField(
            model_name='importtrekline',
            name='pn',
            field=models.FloatField(default=0, verbose_name='Поправка направления'),
        ),
    ]
