# Generated by Django 3.2.13 on 2024-06-08 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0048_alter_importtrek_location_alter_importtrek_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldLine',
        ),
        migrations.DeleteModel(
            name='WorldPoint',
        ),
        migrations.AlterModelOptions(
            name='importinc',
            options={'verbose_name_plural': 'Импорт точек инцендента'},
        ),
        migrations.AlterField(
            model_name='importinc',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местонахождение инцедентов'),
        ),
        migrations.AlterField(
            model_name='importinc',
            name='name',
            field=models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Название инцендента'),
        ),
    ]
