# Generated by Django 3.2.13 on 2024-06-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0049_auto_20240608_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Имя сотрудника')),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'person_model',
            },
        ),
        migrations.AlterModelOptions(
            name='pointinline',
            options={'verbose_name_plural': 'Таблица M:N точки-линии'},
        ),
        migrations.AlterModelTable(
            name='pointinline',
            table='relations_p_l_model',
        ),
        migrations.CreateModel(
            name='IncInPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incendent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='geoapp.importinc')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incendent', to='geoapp.person')),
            ],
            options={
                'verbose_name_plural': 'Таблица M:N сотрудники-инценденты',
                'db_table': 'relations_inc_pers_model',
            },
        ),
    ]
