# Generated by Django 5.0 on 2024-06-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0050_auto_20240608_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importinc',
            unique_together={('name', 'location')},
        ),
    ]
