# Generated by Django 4.0.3 on 2024-06-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0051_alter_importinc_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importinc',
            unique_together=set(),
        ),
    ]
