# Generated by Django 3.2.13 on 2024-06-18 06:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0055_alter_importinc_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importinc',
            options={'verbose_name_plural': 'Импорт точек инцидента'},
        ),
        migrations.AlterModelOptions(
            name='incinperson',
            options={'verbose_name_plural': 'Таблица M:N сотрудники-инциденты'},
        ),
        migrations.AlterField(
            model_name='importinc',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местонахождение инцидентов'),
        ),
        migrations.AlterField(
            model_name='importinc',
            name='name',
            field=models.CharField(blank=True, default=' - ', max_length=250, verbose_name='Название инцидента'),
        ),
    ]
