# Generated by Django 3.2.13 on 2024-06-18 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0056_auto_20240618_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('stop', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
    ]
