# Generated by Django 3.2.13 on 2024-06-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0057_groops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groops',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groops',
            name='stop',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
