# Generated by Django 3.2.13 on 2024-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0058_auto_20240618_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groops',
            name='title',
        ),
        migrations.AddField(
            model_name='groops',
            name='id_groop',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
