# Generated by Django 4.0.3 on 2024-06-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0059_auto_20240618_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groops',
            new_name='Groups',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='id_groop',
            new_name='id_group',
        ),
    ]
