# Generated by Django 4.0.3 on 2024-06-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0062_alter_groups_id_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='bool_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id_group',
            field=models.IntegerField(),
        ),
    ]
