# Generated by Django 4.0.3 on 2024-06-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0063_alter_groups_bool_stop_alter_groups_id_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='id_group',
            new_name='idgroup',
        ),
    ]
