# Generated by Django 4.0.3 on 2024-06-19 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0064_rename_id_group_groups_idgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groups',
            name='stop',
            field=models.DateTimeField(),
        ),
    ]
