# Generated by Django 4.0.3 on 2024-06-19 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0067_alter_groups_start_alter_groups_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groups',
            name='stop',
            field=models.DateTimeField(blank=True),
        ),
    ]
