# Generated by Django 4.0.3 on 2024-06-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0070_alter_groups_start_alter_groups_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='stop',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
