# Generated by Django 4.0.3 on 2024-06-21 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0074_alter_groups_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groups',
            name='stop',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
