# Generated by Django 4.0.3 on 2024-06-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0083_alter_groups_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='stop',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
