# Generated by Django 3.2.13 on 2024-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0084_alter_groups_stop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importinc',
            options={'ordering': ['name'], 'verbose_name_plural': 'Импорт точек инцидента'},
        ),
        migrations.AlterField(
            model_name='groups',
            name='result',
            field=models.CharField(blank=True, default=' группа не завершила маршрут ', max_length=250, verbose_name='Время на маршруте, секунды'),
        ),
    ]
