# Generated by Django 4.2.5 on 2023-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Марка')),
                ('image', models.URLField()),
                ('price', models.IntegerField()),
                ('release_date', models.DateField(auto_now_add=True)),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
