# Generated by Django 3.2.13 on 2023-12-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0014_worldpoint_pn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldpoint',
            name='pn',
        ),
        migrations.AddField(
            model_name='worldline',
            name='pn',
            field=models.FloatField(default=1, help_text='Поправка направления', verbose_name='Поправка направления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worldline',
            name='azimuth',
            field=models.CharField(blank=True, default=' - ', help_text='Значение азимута магнитного с учетом поправки направления', max_length=250, verbose_name='Значение азимута магнитного'),
        ),
    ]
