# Generated by Django 4.2.5 on 2023-11-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_options_remove_student_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher', to='school.teacher'),
        ),
    ]
