# Generated by Django 4.2.7 on 2023-11-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlescope_is_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='is_main',
        ),
    ]
