# Generated by Django 4.2.7 on 2023-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_articlescope_is_main_scope_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
