# Generated by Django 4.2.7 on 2023-11-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_options_tags_is_main_alter_tags_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsarticle',
            name='is_main',
        ),
    ]
