# Generated by Django 4.2.7 on 2023-11-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_tags_is_main_article_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_main',
        ),
        migrations.AddField(
            model_name='tagsarticle',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
