# Generated by Django 4.2.7 on 2023-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_article_is_main_tagsarticle_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='articles.TagsArticle', to='articles.article'),
        ),
    ]
